config/routes.rb
Rails.application.routes.draw do
  get 'bookings/index'
  devise_for :users
  get 'welcome/index'
  get 'afavourites/create' => "afavourites#create"
  #post '/afavourites/create', to: "afavourites#create"
  put "roles/:id/activate" => "roles#activate", :as => "active_role"
  #post 'afavourites/:id/build' => "afavourites#build", as: 'build_afavourites'
  resources :hotels do
  	resources :comments
  	resources :afavourites
    resources :bookings
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/afavourite.rb
class Afavourite < ApplicationRecord

  belongs_to :hotel, optional: true
  belongs_to :user, optional: true, dependent: :destroy
  #attr_accessor :userid, :hotelid
  validates :userid, :hotelid, presence: true
end

app/controllers/afavourites_controller.rb
class AfavouritesController < ApplicationController
	 def index
		@afavourite = Afavourite.where(userid: current_user.id)
	 end

	def create
		@hotel = Hotel.find_by_id(params[:hotel_id])
	    #if current_user.afavourites.exists?(:hotelid => @hotel.id)
	    if 	Afavourite.exists?(userid: current_user.id, hotelid: @hotel.id)
	          redirect_to hotel_afavourites_path(:hotelid, :id), alert: 'This hotel is already in your favourite list'
	    else
	    	  @afavourite = @hotel.afavourites.create({userid: current_user.id, hotelid: params[:hotel_id]})
		      @afavourite.save
		      if @afavourite.save
		      redirect_to hotel_path(@hotel), notice: 'Hotel has been favorited'
		      else
		      redirect_to @hotel, alert: 'Something went wrong...*sad panda*'
		      end
	    end
	end

	def destroy
	    @hotel = Hotel.find_by_id(params[:hotel_id])
	    @afavourite =  @hotel.afavourites.find_by_id(params[:afavourite_id] || params[:id])
	    @afavourite.destroy if !@afavourite.nil?
	    redirect_to hotel_path(@hotel), notice: 'Hotel is no longer in your favorites'
	end

 	def new
	 	@afavourite = Afavourite.new
	end
end

app/helpers/afavourites_helper.rb
module AfavouritesHelper
end

app/views/afavourites/index.html.erb
<div class="navbar-text">
<h1><strong>Listing - Favourites</strong></h1>
</div>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="<%=root_path%>">Home</a></li>
    <li class="breadcrumb-item"><a href="<%=hotels_path%>">Hotels</a></li>
    <li class="breadcrumb-item active" aria-current="page">Favourites</li>
  </ol>
</nav>

	<table class="table">
    <tr>
      <th>User_Name</th>
      <th>Hotel_Name</th>
      <th>Hotel_type</th>
      <th>Average_cost</th>
      <th></th>
    </tr>

    <% @afavourite.each do |f| %>
      <tr>
        <td><%= current_user.fname%></td>
        <td><%= f.hotel.name if f.hotel %></td>
        <td><%= f.hotel.hoteltype if f.hotel %></td>
        <td><%= f.hotel.avgcost if f.hotel %></td>
        <td><%= link_to 'show', hotel_path(f.hotel_id, f, params[:hotelid]), :class => "btn btn-primary" %></td>   
        <td><%= link_to 'Un-favourite', hotel_afavourite_path(f.hotelid, f, params[:hotelid]),               
                 method: :delete,
                 data: { confirm: 'Are you sure?' }, notice: 'UnFavoured Hotel Successfully', :class => "btn btn-outline-danger" %></td>
      </tr>
    <% end %>
</table>