config/routes.rb
Rails.application.routes.draw do
  get 'bookings/index'
  devise_for :users
  get 'welcome/index'
  get 'afavourites/create' => "afavourites#create"
  #post '/afavourites/create', to: "afavourites#create"
  put "roles/:id/activate" => "roles#activate", :as => "active_role"
  #post 'afavourites/:id/build' => "afavourites#build", as: 'build_afavourites'
  resources :hotels do
  	resources :comments
  	resources :afavourites
    resources :bookings
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/hotel.rb
class Hotel < ApplicationRecord
	has_many :users, :through => :afavourite
	has_many :comments, dependent: :destroy
	has_many :afavourites
	has_many :bookings, dependent: :destroy
	
	mount_uploader :image, ImageUploader
	
	validates :name, :location, :phone, :avgcost, :address, presence: true
	validates :image, file_size: { less_than: 1.megabytes }
	

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
    @hotels = Hotel.all
    @users = User.all
    @afavourites = Afavourite.find_by(params[:afavourite_id] || params[:id])
  end

  def show
    @hotel = Hotel.find_by_id(params[:id] || params[:hotel_id])
  end

  def new
  	@hotel = Hotel.new
  end

  def edit
    @hotel = Hotel.find(params[:id])
  end

  def create
    @hotel = Hotel.new(hotel_params)
    @hotel.userid = current_user.id
    if @hotel.save
      redirect_to @hotel
    else
      render 'new'
    end
  end

def update
  @hotel = Hotel.find(params[:id])
  if @hotel.update(hotel_params)
    redirect_to @hotel
  else
    render 'edit'
  end
end

def destroy
  @hotel = Hotel.find(params[:id])
  @hotel.destroy
  redirect_to @hotel
end

  private
    def hotel_params
      params.require(:hotel).permit(:name, :location, :hoteltype, :phone, :cuisins, :avgcost, :address, :features, :special, :image, :image_cache, :remove_image, :slot1_avail_seat, :slot2_avail_seat) 
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<div class="new-form">
<%= bootstrap_form_with(model: @hotel, local: true) do |form| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@hotel.errors.count, "error") %> prohibited
        this hotel from being saved:
      </h2>
      <ul>
        <% @hotel.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.text_field :name, :class => "form-control" %>
  </div>
  <div>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.text_field :hoteltype %>
  </div>

  <div>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.text_field :cuisins %>
  </div>

  <div>
    <%= form.text_field :avgcost %>
  </div>

  <div>
    <%= form.text_area :address %>
  </div>

   <div>
    <%= form.text_area :features %>
  </div>

   <div>
    <%= form.text_area :special %>
  </div>

  <div>
    <%= form.text_field :slot1_avail_seat %>
  </div>
  </br>
  <div>
    <%= form.text_field :slot2_avail_seat %>
  </div>
  </br>
  <div>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  </br>
  <% if @hotel.image? %>
    <%= image_tag @hotel.image.small_thumb.url %>
    <div>
      <%= label_tag :remove_image do %>
        Remove image
        <%= form.check_box :remove_image %>
      <% end %>
    </div>
  <% end %>
 
  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/hotels/edit.html.erb
<div class="navbar-text">
	<h1><strong>Edit Hotel</strong></h1>
</div>
<br>
 <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<%=root_path%>">Home</a></li>
        <li class="breadcrumb-item"><a href="<%=hotels_path%>">Hotels</a></li>
        <li class="breadcrumb-item"><a href="<%=hotel_path(@hotel)%>"><%=@hotel.name%></a></li>
        <li class="breadcrumb-item"><a aria-current="page">Edit Hotels</a></li>
      </ol>
    </nav>

<%= render 'form' %>

app/views/hotels/index.html.erb
<div class="navbar-text">
  <h1><strong>Listing Hotels</strong></h1>
  </div>
<div class="navbar float-right">
    <!-- <div class="float-sm-right"> -->
      <% if current_user.role == 'admin' %>
      <%= link_to 'Create New Hotel', new_hotel_path, :class => "btn btn-primary float-right" %>
      <% end %>
      <% if current_user.role == 'member'%>
      <%= link_to 'My Favourites', hotel_afavourites_path( @hotels), :class => 'btn btn-warning' %>
      <% end %>
    <!-- </div> -->
    </div>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<%=root_path%>">Home</a></li>
        <li class="breadcrumb-item"><a aria-current="page">Hotels</a></li>
      </ol>
    </nav>

<div class="card-group">
  <% @hotels.each do |h| %>
    <% @afavourite = h.afavourites.find_by_id(params[:afavourite_id] || params[:id])%>
    <div class="col-md-4">
      <div class="card">
        <!--<%= link_to(image_tag(h.image.small_thumb.url, alt: 'Image'), h.image.url, target: '_blank') if h.image? %>-->
         <a href="<%=hotel_path(h)%>"> <img class="card-img-top" src="<%=h.image.small_thumb.url%>" alt="Card image cap"></a>
        <div class="card-body">
          <div class="card-header">
            <%= h.name %>
          </div>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
       <!--  <ul class="list-group list-group-flush">
          <li class="list-group-item"><%= h.location %></li>
          <li class="list-group-item"><%= h.phone %></li>
          <li class="list-group-item">Rs.<%= h.avgcost %></li>
        </ul> -->
        </div>
        <div class="card-body text-center">

          <a href="<%=hotel_path(h)%>" class="card-link btn btn-outline-primary btn-sm">View</a>
          <% if current_user.role == 'admin' %>
          <a href="<%=edit_hotel_path(h)%>" class="card-link btn btn-outline-success btn-sm">Update</a>
          <a href="<%=hotel_path(h)%>" class="card-link btn btn-outline-danger btn-sm">Remove</a>
          <% end %>
        </div>
        </div>
    </div>
  <% end %></br>
</div>
<br>
<!-- Section: Contact v.1 -->
<section class="my-5">

  <!-- Section heading -->
  <h2 class="h1-responsive font-weight-bold text-center my-5">Contact us</h2>
  <!-- Section description -->
  <p class="text-center w-responsive mx-auto pb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within a matter of hours to help you.</p>

  <!-- Grid row -->
  <div class="row">

    <!-- Grid column -->
    <div class="col-lg-5 mb-lg-0 mb-4">

      <!-- Form with header -->
      <div class="card">
        <div class="card-body">
          <!-- Header -->
          <div class="form-header blue accent-1">
            <h3 class="mt-2"><i class="fas fa-envelope"></i> Write to us:</h3>
          </div>
          <p class="dark-grey-text">We'll write rarely, but only the best content.</p>
          <!-- Body -->
          <div class="md-form">
            <i class="fas fa-user prefix grey-text"></i>
            <input type="text" id="form-name" class="form-control">
            <label for="form-name">Your name</label>
          </div>
          <div class="md-form">
            <i class="fas fa-envelope prefix grey-text"></i>
            <input type="text" id="form-email" class="form-control">
            <label for="form-email">Your email</label>
          </div>
          <div class="md-form">
            <i class="fas fa-tag prefix grey-text"></i>
            <input type="text" id="form-Subject" class="form-control">
            <label for="form-Subject">Subject</label>
          </div>
          <div class="md-form">
            <i class="fas fa-pencil-alt prefix grey-text"></i>
            <textarea id="form-text" class="form-control md-textarea" rows="3"></textarea>
            <label for="form-text">Send message</label>
          </div>
          <div class="text-center">
            <button class="btn btn-primary">Submit</button>
          </div>
        </div>
      </div>
      <!-- Form with header -->

    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-lg-7">

      <!--Google map-->
      <div id="map-container-section" class="z-depth-1-half map-container-section mb-4" style="height: 400px">
        <iframe src="https://maps.google.com/maps?q=chennai&t=&z=15&ie=UTF8&iwloc=&output=embed" frameborder="0"
          style="border:0" allowfullscreen></iframe>
      </div>
      <!-- Buttons-->
      <div class="row text-center">
        <div class="col-md-4">
          <a class="btn-floating blue accent-1">
            <i class="fas fa-map-marker-alt"></i>
          </a>
          <p>Chennai, 94126</p>
          <p class="mb-md-0">India</p>
        </div>
        <div class="col-md-4">
          <a class="btn-floating blue accent-1">
            <i class="fas fa-phone"></i>
          </a>
          <p>+ 01 234 567 89</p>
          <p class="mb-md-0">Mon - Fri, 8:00-22:00</p>
        </div>
        <div class="col-md-4">
          <a class="btn-floating blue accent-1">
            <i class="fas fa-envelope"></i>
          </a>
          <p>re-servehotels@gmail.com</p>
          <p class="mb-0">service@gmail.com</p>
        </div>
      </div>

    </div>
    <!-- Grid column -->

  </div>
  <!-- Grid row -->

</section>
<!-- Section: Contact v.1 -->

app/views/hotels/new.html.erb
<div class="navbar-text">
	<h1><strong>New Hotel</strong></h1>	
</div>

 <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<%=root_path%>">Home</a></li>
        <li class="breadcrumb-item"><a href="<%=hotels_path%>">Hotels</a></li>
        <li class="breadcrumb-item"><a aria-current="page">New Hotel</a></li>
      </ol>
    </nav>
    <div class="card-group">
    	<div class="card" style="width: 21rem">
    		<%= render 'form' %>
    	</div>
    	<div class="card">
    		<%= image_tag("front2.jpg", class: "img-responsive img-thumbnail img-circle") %>
    		<%= image_tag("front4.jpg", class: "img-responsive img-thumbnail img-circle") %>
    		<%= image_tag("Front1.jpg", class: "img-responsive img-thumbnail img-circle") %>
    		<%= image_tag("front3.png", class: "img-responsive img-thumbnail img-circle") %>
    	</div>
    </div>
<br><br>

app/views/hotels/show.html.erb
<div class="navbar-text">
    <h2><strong><%= @hotel.name %></strong></h2>
    <p><%= @hotel.address %></p>
  </div>
<div class="navbar float-right">
  <div class="float-sm-right">
   <% if current_user.role == 'admin' %>
      <%= link_to 'Update Hotel', edit_hotel_path(@hotel), :class => 'btn btn-success' %>
    <% end %>
    <%= link_to 'View Bookings', hotel_bookings_path(@hotel), :class => 'btn btn-primary' %>
  </div>
</div>

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<%=root_path%>">Home</a></li>
        <li class="breadcrumb-item"><a href="<%=hotels_path%>">Hotels</a></li>
        <li class="breadcrumb-item active" aria-current="page"><%= @hotel.name %></li>
      </ol>
    </nav>
<div class="card-group">
<div class="card">
<img class="card" src="<%=@hotel.image.thumb.url%>" alt="Card image cap" style="height: 30rem">
</div>
<div class="card">
  <h5 class="card-header">Featured</h5>
  <div class="card-body">
    <h5 class="card-title"><%= @hotel.name %></h5>
    <p class="card-text"><%= @hotel.location %></p>
    <p class="card-text"><%= @hotel.hoteltype %></p>
    <p class="card-text"><%= @hotel.phone %></p>
    <p class="card-text"><%= @hotel.cuisins %></p>
    <p class="card-text"><%= @hotel.avgcost %></p>
    <p class="card-text"><%= @hotel.address %></p>
    <p class="card-text"><%= @hotel.features %></p>
    <p class="card-text"><%= @hotel.special %></p>
    <% if current_user.role == 'user' || current_user.role == 'member' %>
    <a href="<%=new_hotel_booking_path(@hotel)%>" class="btn btn-primary">Book now!</a>
    <% end %>
    <% if current_user.role == 'member' %>
    <%= link_to 'Add to favorites', hotel_afavourites_path(@hotel.id), method: :post, :class => "btn btn-warning" %>
    <% end %>
  </div>
</div>
</div>

<br>

<div>
  <h3><strong>Leave a comment:</strong></h3>
  <%= render 'comments/form' %>
</div>

<br>

<div>
  <h3><strong>Comments Left:</strong></h3>
  <div class="card-deck">
    <%= render @hotel.comments %>
  </div> 
</div>

<br>

<!-- <%= image_tag(@hotel.image.url, alt: 'Image') if @hotel.image? %> -->